<?php

define('DEFAULT_EVENT','default_event');
include_once('cod_events.features.inc');

/**
 * Implements hook_menu_alter().
 * Change the OG 'groups' hook to be an event instead.
 */
function cod_events_menu_alter(&$items) {
  if (isset($items['node/%/group'])) {
    $items['node/%/group']['access callback'] = 'cod_events_get_group_admin';

    /*
    $items['node/%/event/dashboard'] = array(
      'title' => 'Dashboard',
      'weight' => -10,
      'type' => MENU_DEFAULT_LOCAL_TASK,
    );
    */
  }
  if (isset($items['node/%/tickets'])) {
    $items['node/%/tickets']['access callback'] = 'cod_events_get_ticket_admin';
    $items['node/%/event/tickets'] = $items['node/%/tickets'];
    $items['node/%/event/tickets']['access arguments'][] = TRUE;
  }
}

/*
 * Make the event dashboard be an admin path
 */
function cod_schedule_admin_paths() {
  $paths = array(
    'node/*/event' => TRUE,
    'node/*/event/*' => TRUE,
  );
  return $paths;
}

/**
 * Implements hook_permission().
 */
function cod_events_permission() {
  $perms = array();

  $perms['view program'] = array(
    'title' => t('View Program'),
    'description' => t('Allows users to view the program.'),
  );
  return $perms;
}

/*
 * Menu Alter access callback.
 * Allows OG to be used elsewhere on the site, but will make the group tab
 * disappear when used on the event content type.
 */
function cod_events_get_group_admin($entity_type, $etid, $event = FALSE) {
  // If we're not dealing with nodes, we aren't dealing with events. Skip.
  if ($entity_type != 'node') {
    return og_ui_get_group_admin($entity_type, $etid);
  }
  $entity = node_load($etid);
  if (isset($entity->type) && $entity->type == 'event' && $event == TRUE) {
    return og_ui_get_group_admin($entity_type, $etid);
  }
  return FALSE;
}

/**
 * Menu Alter access callback.
 * Allows Tickets to be used elsewhere on the site, but will make the ticket tab
 * disappear when used on the event content type.
 */
function cod_events_get_ticket_admin($entity_type, $etid, $op, $event = FALSE) {
  // If we're not dealing with nodes, we aren't dealing with events. Skip.
  if ($entity_type != 'node') {
    return ticket_type_overview_access($entity_type, $etid, $op);
  }
  $entity = node_load($etid);
  if (isset($entity->type) && $entity->type == 'event' && $event == TRUE) {
    return ticket_type_overview_access($entity_type, $etid, $op);
  }
  return FALSE;
}

/*
* Implements hook_ctools_plugin_directory -
* This lets ctools know to scan my module for a content_type plugin file
* Detailed docks in ctools/ctools.api.php
*/
function cod_events_ctools_plugin_directory($module, $plugin) {
  // we'll be nice and limit scandir() calls
  if ($module == 'ctools' && $plugin == 'content_types') {
    return 'plugins/content_types';
  }
  if ($module == 'entityreference') {
    return "plugins/entityreference/$plugin";
  }
}

/**
 * Implements hook_og_user_access_alter().
 *
 * Borrowed from commons_groups.
 * Todo: Abstract out commons groups so group visibility can by used elsewhere.
 * Allow non-members to post to groups if they have sitewide access.
 */
function cod_events_og_user_access_alter(&$perm, $context) {
  $account = $context['account'];
  $group_type = $context['group_type'];
  $group = $context['group'];

  if ($group_type != 'node') {
    return;
  }
  // The purpose of this function is to grant permissions to create content
  // in a group to non-members of the group, when the group's privacy settings
  // (field_og_subscribe_settings) is set to "Anyone can contribute".
  if (og_is_member($group_type, $group->nid, 'user', $account, array(OG_STATE_ACTIVE, OG_STATE_PENDING, OG_STATE_BLOCKED))) {
    // The user is a group member, so comply to the OG permissions.
    return;
  }

  // See if the Entity allows for non-member postings
  $event_entity_types = cod_events_get_group_content_entity_types();
  foreach ($event_entity_types['node'] as $type => $options) {
    if(isset($options['non_member']) && user_access("create $type content")) {
      $perm["create $type content"] = TRUE;
    }
  }
}

/**
 * Borrowed from commons_groups.
 * Todo: Abstract out commons groups to query event content types.
 * Returns an array of entity types that are enabled via Commons Groups.
 */
function cod_events_get_group_content_entity_types() {
  // Find all Commons Entity integrations.
  $event_entity_integrations = module_invoke_all('event_entity_integration');
  if (empty($event_entity_integrations)) {
    return array();
  }

  foreach ($event_entity_integrations as $entity_type => $integration) {
    foreach ($integration as $bundle => $options) {
      if (isset($options['is_group_content']) && $options['is_group_content'] == FALSE) {
        unset($event_entity_integrations[$entity_type][$bundle]);
      }
    }
    // If an entity type has no integrations, don't return it.
    if (empty($event_entity_integrations[$entity_type])) {
      unset($event_entity_integrations[$entity_type]);
    }
  }

  return $event_entity_integrations;

}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add the default event select box for choosing a default event.
 * This is probably deprecated due to the new event view admin ui.
 */
function cod_events_form_cod_base_admin_settings_alter(&$form, &$form_state, $form_id) {
  $form['cod_events'] = array(
    '#type' => 'fieldset',
    '#title' => t('COD Events'),
    '#weight' => 5,
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
  );

  $options = array(t('No Default Event'));
  $eventQuery = new EntityFieldQuery();
  $event_list =  $eventQuery->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'event')
    ->propertyCondition('status', 1)
    ->propertyOrderBy('title')
    ->execute();

  if (count($event_list['node']) == 1) {
    $events = array_keys($event_list['node']);
    $default_event = array_pop($events);
    variable_set('cod_events_default_event', $default_event);
    $form['cod_events']['#description'] = t('Node !num is the only event and set to default', array('!num' => $default_event));
  }
  elseif (!empty($event_list['node'])) {
    $events = entity_load('node', array_keys($event_list['node']));
    foreach ($events as $event) {
      $options[$event->nid] = $event->title;
    }

    $form['cod_events']['cod_events_default_event'] = array(
      '#type' => 'select',
      '#title' => t('Default Event'),
      '#options' => $options,
      '#default_value' => variable_get('cod_events_default_event', 0),
    );
  }
  else {
    $form['cod_events']['#markup'] = t('You currently have no events');
    variable_set('cod_events_default_event', 0);
  }

  $form['#submit'][] = 'cod_events_set_default_flag';
}

/**
 * Default event submit handler.
 *
 * This is probably deprecated due to the new event view admin ui.
 */
function cod_events_set_default_flag(&$form, &$form_state) {
  // Kick us out of the flag if we only have one event.
  if (!isset($form_state['values']['cod_events_default_event'])) {
    return;
  }
  if ($form_state['values']['cod_events_default_event']) {
    if ($flag = flag_get_flag('default_event')) {
      $flag->flag('flag', $form_state['values']['cod_events_default_event']);
    }
  }
  else {
    if ($flag = flag_get_flag('default_event')) {
      $flag->flag('unflag', $form['cod_events']['cod_events_default_event']['#default_value']);
    }
  }
}

/**
 * Implements hook_flag_flag().
 */
function cod_events_flag_flag($flag, $entity_id, $account, $flagging) {
  if ($flag->name == 'default_event') {
    variable_set('cod_events_default_event', $entity_id);
  }
}

/**
 * Implements hook_flag_unflag().
 */
function cod_events_flag_unflag($flag, $entity_id, $account, $flagging) {
  if ($flag->name == 'default_event') {
    if ($entity_id == variable_get('cod_events_default_event', 0)) {
      variable_set('cod_events_default_event', 0);
    }
  }
}

/**
* Implements hook_form_alter().
*/
function cod_events_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['og_group_ref'])) {
    // Set the default value if there is none.
    $default_event = isset($_GET['og_group_ref']) ? $_GET['og_group_ref'] : variable_get('cod_events_default_event', 0);

    // Hide the group ref field from non admins.
    if ($default_event && !user_access('administer content')) {
      $form['og_group_ref']['#access'] = FALSE;
    }

    // If there's a default event and the form doesn't have a default value, reload with the default event.
    // TODO: This would probably be better with just a drupal_rebuild_form, but I couldn't get that to work. :(
    if ($default_event && empty($form['og_group_ref']['und'][0]['default']['#default_value'])) {
      drupal_goto(current_path(), array('query' => array('og_group_ref' => $default_event)));
    }
  }
}

/**
 * Append group as query param so new content can have group context.
 */
function cod_events_add_content($event, $content_type) {
  $args = func_get_args();
   // Remove $event from the arguments.
   array_shift($args);
   // Remove $content_type from the arguments.
   array_shift($args);

  $options = array(
    'query' => array(
      'og_group_ref' => $event->nid,
    ),
  );

  if (!empty($args)) {
    $path = implode('/', $args);
    $options['query']['destination'] = '/node/'.$event->nid.'/'.$path;
  }
  drupal_goto('node/add/' . $content_type, $options);
}

/**
 * Callback to send a user back to the admin page after a taxonomy item is created.
 */
function cod_events_add_term($event, $vocabulary) {
  $args = func_get_args();
   // Remove $event from the arguments.
   array_shift($args);
   // Remove $vocabulary from the arguments.
   array_shift($args);

  $options = array();
  if (!empty($args)) {
    $path = implode('/', $args);
    $options['query']['destination'] = '/node/'.$event->nid.'/'.$path;
  }
  // Check to see if we're using a OG Vocabulary. Probably better way to do this.
  if ($vocab = taxonomy_vocabulary_machine_name_load($vocabulary . '_' . $event->nid)) {
    drupal_goto('admin/structure/taxonomy/' . $vocabulary . '_' . $event->nid . '/add', $options);
  }
  else if ($vocab = taxonomy_vocabulary_machine_name_load($vocabulary)) {
    drupal_goto('admin/structure/taxonomy/' . $vocabulary . '/add', $options);
  }
  else {
    drupal_set_message("Vocabulary '$vocabulary' was not found.", 'warning');
    drupal_goto($options['query']['destination']);
  }
}