<?php
/**
 * @file
 * Code for the Showcase feature.
 */

include_once 'showcase.features.inc';



/*
 * Prevent Token recursion
 */
function showcase_preprocess_token_tree(&$variables) {
  if (is_array($variables['token_types']) && array_intersect(array('node', 'user'), $variables['token_types'])) {
    $variables['recursion_limit'] = 2;
  }
}


function showcase_theme_registry_alter(&$theme_registry) {
  $theme_registry['page__node__showcase'] = array(
    'type' => 'module',
    'path' => drupal_get_path('module', 'showcase'),
    'template' => '/theme/page/page--node--showcase',
  );
  $theme_registry['page__showcase'] = array(
    'type' => 'module',
    'path' => drupal_get_path('module', 'showcase'),
    'template' => '/theme/page/page--showcase',
  );
  $theme_registry['page__auto_showcase'] = array(
    'type' => 'module',
    'path' => drupal_get_path('module', 'showcase'),
    'template' => '/theme/page/page--auto-showcase',
  );
  $theme_registry['views_view__showcase__auto_showcase'] = array(
    'base hook' => 'views_view',
    'type' => 'module',
    'path' => drupal_get_path('module', 'showcase') . '/theme/views',
    'template' => '/views-view--showcase--auto-showcase',
  );
  $theme_registry['views_view__showcase__showcase'] = array(
    'base hook' => 'views_view',
    'type' => 'module',
    'path' => drupal_get_path('module', 'showcase') . '/theme/views',
    'template' => '/views-view--showcase--showcase',
  );
  $theme_registry['views_view__showcase__showcase_node'] = array(
    'base hook' => 'views_view',
    'type' => 'module',
    'path' => drupal_get_path('module', 'showcase') . '/theme/views',
    'template' => '/views-view--showcase--showcase-node',
  );
  $theme_registry['views_view_field__showcase__nothing'] = array(
    'base hook' => 'views_view',
    'type' => 'module',
    'path' => drupal_get_path('module', 'showcase') . '/theme/views',
    'template' => '/views-view-field--showcase--nothing',
  );

}
